require 'pathname'

ws_dir = Pathname.new(__dir__)
ws_dir = ws_dir.parent until
  File.exist?("#{ws_dir}/node_modules/react-native-macos/scripts/react_native_pods.rb") ||
  ws_dir.expand_path.to_s == '/'
require "#{ws_dir}/node_modules/react-native-macos/scripts/react_native_pods.rb"

prepare_react_native_project!

target 'MdViewer-macOS' do
  platform :macos, '14.0'
  use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => '../node_modules/react-native-macos',
    :fabric_enabled => ENV['RCT_NEW_ARCH_ENABLED'] == '1',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer)

    # react-native-fs still declares :osx => "10.13"; Xcode 27 refuses anything below 12.0.
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        target = config.build_settings['MACOSX_DEPLOYMENT_TARGET']
        if target && Gem::Version.new(target) < Gem::Version.new('14.0')
          config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '14.0'
        end
      end
    end
  end
end
